# Production Docker Compose Configuration with SSL/HTTPS
version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: fragrance-ai-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro
    depends_on:
      - backend
      - frontend
    networks:
      - fragrance-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: fragrance-ai-backend
    restart: unless-stopped
    expose:
      - "8000"
    environment:
      - ENVIRONMENT=production
      - CORS_ORIGINS=["https://fragrance-ai.com"]
    networks:
      - fragrance-network

  frontend:
    build:
      context: ./commerce
      dockerfile: Dockerfile
    container_name: fragrance-ai-frontend
    restart: unless-stopped
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
    networks:
      - fragrance-network

networks:
  fragrance-network:
    driver: bridge
